## Netlify configuration for Identity + protected members area

[build]
  publish = "public"
  functions = "netlify/functions"

## Role-based access to members area on the CDN edge.
## Requires the browser to send nf_jwt cookie (set in auth.js after login).
[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  force = true
  conditions = { Role = ["admin", "active", "hour", "day", "week", "month", "halfyear", "year"] }

## Fallback: anyone without the role gets redirected to login.
[[redirects]]
  from = "/members/*"
  to = "/login/"
  status = 302
  force = true

## Convenience routing for pretty URLs
[[redirects]]
  from = "/login"
  to = "/login/index.html"
  status = 200

[[redirects]]
  from = "/members"
  to = "/members/index.html"
  status = 200

## Strong no-cache for members to avoid stale authenticated content
[[headers]]
  for = "/members/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

## Also avoid caching for login page to keep auth state fresh
[[headers]]
  for = "/login/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
